apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: eco-content-secrets
  namespace: prod
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/eco-futures-f862e/secrets/HOST_CONTENT_PROD/versions/latest"
        fileName: "HOST"
      - resourceName: "projects/eco-futures-f862e/secrets/APP_KEYS_CONTENT_PROD/versions/latest"
        fileName: "APP_KEYS"
      - resourceName: "projects/eco-futures-f862e/secrets/API_TOKEN_SALT_CONTENT_PROD/versions/latest"
        fileName: "API_TOKEN_SALT"
      - resourceName: "projects/eco-futures-f862e/secrets/ADMIN_JWT_SECRET_CONTENT_PROD/versions/latest"
        fileName: "ADMIN_JWT_SECRET"
      - resourceName: "projects/eco-futures-f862e/secrets/TRANSFER_TOKEN_SALT_CONTENT_PROD/versions/latest"
        fileName: "TRANSFER_TOKEN_SALT"
      - resourceName: "projects/eco-futures-f862e/secrets/DATABASE_CLIENT_CONTENT_PROD/versions/latest"
        fileName: "DATABASE_CLIENT"
      - resourceName: "projects/eco-futures-f862e/secrets/DATABASE_HOST_CONTENT_PROD/versions/latest"
        fileName: "DATABASE_HOST"
      - resourceName: "projects/eco-futures-f862e/secrets/DATABASE_PORT_CONTENT_PROD/versions/latest"
        fileName: "DATABASE_PORT"
      - resourceName: "projects/eco-futures-f862e/secrets/DATABASE_NAME_CONTENT_PROD/versions/latest"
        fileName: "DATABASE_NAME"
      - resourceName: "projects/eco-futures-f862e/secrets/DATABASE_USERNAME_CONTENT_PROD/versions/latest"
        fileName: "DATABASE_USERNAME"
      - resourceName: "projects/eco-futures-f862e/secrets/DATABASE_PASSWORD_CONTENT_PROD/versions/latest"
        fileName: "DATABASE_PASSWORD"
      - resourceName: "projects/eco-futures-f862e/secrets/DATABASE_SSL_CONTENT_PROD/versions/latest"
        fileName: "DATABASE_SSL"
      - resourceName: "projects/eco-futures-f862e/secrets/JWT_SECRET_CONTENT_PROD/versions/latest"
        fileName: "JWT_SECRET"
      - resourceName: "projects/eco-futures-f862e/secrets/GCS_BUCKET_NAME_CONTENT_PROD/versions/latest"
        fileName: "GCS_BUCKET_NAME"
      - resourceName: "projects/eco-futures-f862e/secrets/GCS_SERVICE_TYPE_CONTENT_PROD/versions/latest"
        fileName: "GCS_SERVICE_TYPE"
      - resourceName: "projects/eco-futures-f862e/secrets/GCS_PROJECT_ID_CONTENT_PROD/versions/latest"
        fileName: "GCS_PROJECT_ID"
      - resourceName: "projects/eco-futures-f862e/secrets/GCS_PRIVATE_KEY_ID_CONTENT_PROD/versions/latest"
        fileName: "GCS_PRIVATE_KEY_ID"
      - resourceName: "projects/eco-futures-f862e/secrets/GCS_PRIVATE_KEY_CONTENT_PROD/versions/latest"
        fileName: "GCS_PRIVATE_KEY"
      - resourceName: "projects/eco-futures-f862e/secrets/GCS_CLIENT_EMAIL_CONTENT_PROD/versions/latest"
        fileName: "GCS_CLIENT_EMAIL"
      - resourceName: "projects/eco-futures-f862e/secrets/GCS_CLIENT_ID_CONTENT_PROD/versions/latest"
        fileName: "GCS_CLIENT_ID"
      - resourceName: "projects/eco-futures-f862e/secrets/GCS_CLIENT_CERT_URL_CONTENT_PROD/versions/latest"
        fileName: "GCS_CLIENT_CERT_URL"
      - resourceName: "projects/eco-futures-f862e/secrets/GCS_BASE_PATH_CONTENT_PROD/versions/latest"
        fileName: "GCS_BASE_PATH"
      - resourceName: "projects/eco-futures-f862e/secrets/GCS_BASE_URL_CONTENT_PROD/versions/latest"
        fileName: "GCS_BASE_URL"

  secretObjects:
    - secretName: eco-content-env
      type: Opaque
      data:
        - objectName: HOST
          key: HOST
        - objectName: APP_KEYS
          key: APP_KEYS
        - objectName: API_TOKEN_SALT
          key: API_TOKEN_SALT
        - objectName: ADMIN_JWT_SECRET
          key: ADMIN_JWT_SECRET
        - objectName: TRANSFER_TOKEN_SALT
          key: TRANSFER_TOKEN_SALT
        - objectName: DATABASE_CLIENT
          key: DATABASE_CLIENT
        - objectName: DATABASE_HOST
          key: DATABASE_HOST
        - objectName: DATABASE_PORT
          key: DATABASE_PORT
        - objectName: DATABASE_NAME
          key: DATABASE_NAME
        - objectName: DATABASE_USERNAME
          key: DATABASE_USERNAME
        - objectName: DATABASE_PASSWORD
          key: DATABASE_PASSWORD
        - objectName: DATABASE_SSL
          key: DATABASE_SSL
        - objectName: JWT_SECRET
          key: JWT_SECRET
        - objectName: GCS_BUCKET_NAME
          key: GCS_BUCKET_NAME
        - objectName: GCS_SERVICE_TYPE
          key: GCS_SERVICE_TYPE
        - objectName: GCS_PROJECT_ID
          key: GCS_PROJECT_ID
        - objectName: GCS_PRIVATE_KEY_ID
          key: GCS_PRIVATE_KEY_ID
        - objectName: GCS_PRIVATE_KEY
          key: GCS_PRIVATE_KEY
        - objectName: GCS_CLIENT_EMAIL
          key: GCS_CLIENT_EMAIL
        - objectName: GCS_CLIENT_ID
          key: GCS_CLIENT_ID
        - objectName: GCS_CLIENT_CERT_URL
          key: GCS_CLIENT_CERT_URL
        - objectName: GCS_BASE_PATH
          key: GCS_BASE_PATH
        - objectName: GCS_BASE_URL
          key: GCS_BASE_URL