apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: eco-api-secrets
  namespace: prod
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/eco-futures-f862e/secrets/API_HOSTNAME_PROD/versions/latest"
        fileName: "API_HOSTNAME"
      - resourceName: "projects/eco-futures-f862e/secrets/APP_PORT_PROD/versions/latest"
        fileName: "APP_PORT"
      - resourceName: "projects/eco-futures-f862e/secrets/CACHE_TTL_PROD/versions/latest"
        fileName: "CACHE_TTL"
      - resourceName: "projects/eco-futures-f862e/secrets/ECO_API_DB_HOST_PROD/versions/latest"
        fileName: "ECO_API_DB_HOST"
      - resourceName: "projects/eco-futures-f862e/secrets/ECO_API_DB_NAME_PROD/versions/latest"
        fileName: "ECO_API_DB_NAME"
      - resourceName: "projects/eco-futures-f862e/secrets/ECO_API_DB_PASS_PROD/versions/latest"
        fileName: "ECO_API_DB_PASS"
      - resourceName: "projects/eco-futures-f862e/secrets/ECO_API_DB_PORT_PROD/versions/latest"
        fileName: "ECO_API_DB_PORT"
      - resourceName: "projects/eco-futures-f862e/secrets/ECO_API_DB_USER_PROD/versions/latest"
        fileName: "ECO_API_DB_USER"
      - resourceName: "projects/eco-futures-f862e/secrets/ENV_PROD/versions/latest"
        fileName: "ENV"
      - resourceName: "projects/eco-futures-f862e/secrets/ES_API_KEY_PROD/versions/latest"
        fileName: "ES_API_KEY"
      - resourceName: "projects/eco-futures-f862e/secrets/ES_NODE_URL_PROD/versions/latest"
        fileName: "ES_NODE_URL"
      - resourceName: "projects/eco-futures-f862e/secrets/GOOGLE_MAPS_API_KEY_PROD/versions/latest"
        fileName: "GOOGLE_MAPS_API_KEY"
      - resourceName: "projects/eco-futures-f862e/secrets/JWT_SECRET_PROD/versions/latest"
        fileName: "JWT_SECRET"
      - resourceName: "projects/eco-futures-f862e/secrets/PKEY_ADMIN_PROD/versions/latest"
        fileName: "PKEY_ADMIN"
      - resourceName: "projects/eco-futures-f862e/secrets/REDIS_HOST_PROD/versions/latest"
        fileName: "REDIS_HOST"
      - resourceName: "projects/eco-futures-f862e/secrets/REDIS_PORT_PROD/versions/latest"
        fileName: "REDIS_PORT"
      - resourceName: "projects/eco-futures-f862e/secrets/REPLICAS_PROD/versions/latest"
        fileName: "REPLICAS"
      - resourceName: "projects/eco-futures-f862e/secrets/RPC_URL_1_PROD/versions/latest"
        fileName: "RPC_URL_1"
      - resourceName: "projects/eco-futures-f862e/secrets/SHUFTI_API_URL_PROD/versions/latest"
        fileName: "SHUFTI_API_URL"
      - resourceName: "projects/eco-futures-f862e/secrets/SHUFTI_CALLBACK_URL_PROD/versions/latest"
        fileName: "SHUFTI_CALLBACK_URL"
      - resourceName: "projects/eco-futures-f862e/secrets/SHUFTI_CLIENT_ID_PROD/versions/latest"
        fileName: "SHUFTI_CLIENT_ID"
      - resourceName: "projects/eco-futures-f862e/secrets/SHUFTI_REDIRECT_URL_PROD/versions/latest"
        fileName: "SHUFTI_REDIRECT_URL"
      - resourceName: "projects/eco-futures-f862e/secrets/SHUFTI_SECRET_PROD/versions/latest"
        fileName: "SHUFTI_SECRET"
      - resourceName: "projects/eco-futures-f862e/secrets/SMTP_MAIL_FROM_PROD/versions/latest"
        fileName: "SMTP_MAIL_FROM"
      - resourceName: "projects/eco-futures-f862e/secrets/SMTP_MAIL_HOST_PROD/versions/latest"
        fileName: "SMTP_MAIL_HOST"
      - resourceName: "projects/eco-futures-f862e/secrets/SMTP_MAIL_PASSWORD_PROD/versions/latest"
        fileName: "SMTP_MAIL_PASSWORD"
      - resourceName: "projects/eco-futures-f862e/secrets/SMTP_MAIL_PORT_PROD/versions/latest"
        fileName: "SMTP_MAIL_PORT"
      - resourceName: "projects/eco-futures-f862e/secrets/SMTP_MAIL_SECURE_PROD/versions/latest"
        fileName: "SMTP_MAIL_SECURE"
      - resourceName: "projects/eco-futures-f862e/secrets/SMTP_MAIL_USER_PROD/versions/latest"
        fileName: "SMTP_MAIL_USER"
      - resourceName: "projects/eco-futures-f862e/secrets/SWAGGER_HOST_PROD/versions/latest"
        fileName: "SWAGGER_HOST"
      - resourceName: "projects/eco-futures-f862e/secrets/VERIFICATION_SECRET_PROD/versions/latest"
        fileName: "VERIFICATION_SECRET"
      - resourceName: "projects/eco-futures-f862e/secrets/REACT_APP_API_PATH_PROD/versions/latest"
        fileName: "REACT_APP_API_PATH"
      - resourceName: "projects/eco-futures-f862e/secrets/GOOGLE_CLOUD_CLIENT_EMAIL_DEV/versions/latest"
        fileName: "GOOGLE_CLOUD_CLIENT_EMAIL"
      - resourceName: "projects/eco-futures-f862e/secrets/GOOGLE_CLOUD_PRIVATE_KEY_DEV/versions/latest"
        fileName: "GOOGLE_CLOUD_PRIVATE_KEY"
      - resourceName: "projects/eco-futures-f862e/secrets/GOOGLE_CLOUD_PROJECT_ID_DEV/versions/latest"
        fileName: "GOOGLE_CLOUD_PROJECT_ID"
      - resourceName: "projects/eco-futures-f862e/secrets/SERVICE_TYPE_PROD/versions/latest"
        fileName: "SERVICE_TYPE"
   

  secretObjects:
    - secretName: eco-api-env-prod
      type: Opaque
      data:
        - objectName: API_HOSTNAME
          key: API_HOSTNAME
        - objectName: APP_PORT
          key: APP_PORT
        - objectName: CACHE_TTL
          key: CACHE_TTL
        - objectName: ECO_API_DB_HOST
          key: ECO_API_DB_HOST
        - objectName: ECO_API_DB_NAME
          key: ECO_API_DB_NAME
        - objectName: ECO_API_DB_PASS
          key: ECO_API_DB_PASS
        - objectName: ECO_API_DB_PORT
          key: ECO_API_DB_PORT
        - objectName: ECO_API_DB_USER
          key: ECO_API_DB_USER
        - objectName: ENV
          key: ENV
        - objectName: ES_API_KEY
          key: ES_API_KEY
        - objectName: ES_NODE_URL
          key: ES_NODE_URL
        - objectName: GOOGLE_MAPS_API_KEY
          key: GOOGLE_MAPS_API_KEY
        - objectName: JWT_SECRET
          key: JWT_SECRET
        - objectName: PKEY_ADMIN
          key: PKEY_ADMIN
        - objectName: REDIS_HOST
          key: REDIS_HOST
        - objectName: REDIS_PORT
          key: REDIS_PORT
        - objectName: REPLICAS
          key: REPLICAS
        - objectName: RPC_URL_1
          key: RPC_URL_1
        - objectName: SHUFTI_API_URL
          key: SHUFTI_API_URL
        - objectName: SHUFTI_CALLBACK_URL
          key: SHUFTI_CALLBACK_URL
        - objectName: SHUFTI_CLIENT_ID
          key: SHUFTI_CLIENT_ID
        - objectName: SHUFTI_REDIRECT_URL
          key: SHUFTI_REDIRECT_URL
        - objectName: SHUFTI_SECRET
          key: SHUFTI_SECRET
        - objectName: SMTP_MAIL_FROM
          key: SMTP_MAIL_FROM
        - objectName: SMTP_MAIL_HOST
          key: SMTP_MAIL_HOST
        - objectName: SMTP_MAIL_PASSWORD
          key: SMTP_MAIL_PASSWORD
        - objectName: SMTP_MAIL_PORT
          key: SMTP_MAIL_PORT
        - objectName: SMTP_MAIL_SECURE
          key: SMTP_MAIL_SECURE
        - objectName: SMTP_MAIL_USER
          key: SMTP_MAIL_USER
        - objectName: SWAGGER_HOST
          key: SWAGGER_HOST
        - objectName: VERIFICATION_SECRET
          key: VERIFICATION_SECRET
        - objectName: REACT_APP_API_PATH
          key: REACT_APP_API_PATH
        - objectName: GOOGLE_CLOUD_CLIENT_EMAIL
          key: GOOGLE_CLOUD_CLIENT_EMAIL
        - objectName: GOOGLE_CLOUD_PRIVATE_KEY
          key: GOOGLE_CLOUD_PRIVATE_KEY
        - objectName: GOOGLE_CLOUD_PROJECT_ID
          key: GOOGLE_CLOUD_PROJECT_ID
        - objectName: SERVICE_TYPE
          key: SERVICE_TYPE
    
        

