apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: eco-kyc-secrets
  namespace: prod
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/eco-futures-f862e/secrets/WEBHOOK_SIGNING_SECRET_KYC-PROD/versions/latest"
        fileName: "WEBHOOK_SIGNING_SECRET"
      - resourceName: "projects/eco-futures-f862e/secrets/AWS_ACCESS_KEY_ID_KYC-PROD/versions/latest"
        fileName: "AWS_ACCESS_KEY_ID"
      - resourceName: "projects/eco-futures-f862e/secrets/AWS_SECRET_ACCESS_KEY_KYC-PROD/versions/latest"
        fileName: "AWS_SECRET_ACCESS_KEY"


  secretObjects:
    - secretName: eco-kyc-env-prod
      type: Opaque
      data:
        - objectName: WEBHOOK_SIGNING_SECRET
          key: WEBHOOK_SIGNING_SECRET
        - objectName: AWS_ACCESS_KEY_ID
          key: AWS_ACCESS_KEY_ID
        - objectName: AWS_SECRET_ACCESS_KEY
          key: AWS_SECRET_ACCESS_KEY
